* shka-ont-rnaseq-preprocess

An optimized preprocess pipeline for Oxford Nanopore RNAseq. A
detailed document will come soon.

* Getting Started

Required software packages for this pipeline is managed by Conda. See [[https://docs.conda.io/en/latest/miniconda.html][the instruction]] to install Conda. Also a script =bin/install_miniconda.sh= in this package would be helpful for *nix users. However, the installation will change your base envronment. If you don't want to change it, the pipeline should be installed in a virturl environment (ex. by VirtualBox, Docker or OpenStack). After the installation of Conda, when you proceed a preprocess named =test=,

#+begin_src shell :exec never
  conda create --name test
  conda activate test
  git checkout https://github.com/shka/shka-ont-rnaseq-preprocess.git test
  cd test
  bin/install.sh
#+end_src

Edit =config.yml= for your preprocess, then run the preprocess pipeline as below. Change the number for =--cores= according to your environment.

#+begin_src shell :exec never
  snakemake --cores=6 all
#+end_src

* License

See ./LICENSE
